openapi: 3.0.0
info:
  title: Skupply
  description: Piattaforma per la compravendita di articoli scolastici
  contact:
    name: Piccin Andrea - Di Zepp Dorijan - Rossi Simone
    email: andrea.piccin@studenti.unitn.it
  licence:
    name: MIT
    url: https://opensource.org/licenses/MIT

  version: 0.1.0

servers:
  - url:  "http://localhost:3000"
    description: Internal Testing Server

paths:
  $ref: "./paths/index.yaml"

components:
  schemas:
    $ref: "./components/schemas/index.yaml"
  
  securitySchemes:
    ApiKeyAuth:
        type: apiKey
        description: per ottenere il token, utilizzare l'api login presente nel tag Authentication e recuperarlo dal messaggio
                    di risposta
        in: header
        name: x-access-token